version: "3.5"

services:
  postgres:
    container_name: flask_db
    image: postgres
    environment:
      POSTGRES_USER: "flask"
      POSTGRES_PASSWORD: "flask"
      POSTGRES_DB: "flask_db"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
